#!/bin/bash

idx_link="[index](./index.html)"

for p in "$@"
do
    echo Exportando "$p" como ../"${p/.md/}".html
    { printf "%s\n\n" $idx_link; cat "$p" ; } | pandoc  -s -o ../"${p/.md/}".html
done

