#!/bin/bash

if [ -z $( type -t echo_index_path ) ]; then . funcs.sh ;fi


idx_link=$( echo_index_path  1 )




for dir in "$(ls -d */)"
do
    destino=${PWD/contenido\//}/"${dir}"index.html
    echo Exportando   ${PWD/contenido\//}/"${dir}"index.html
    cd ${dir}

    { printf "%s\n\n" "$idx_link" ; . subtemas.sh ; } \
	| pandoc -s --webtex -o ${destino}

    cd ..
done

